// Package embedding provides interfaces and implementations for text embedding generation.
// It supports both local and remote embedding models with batch processing and caching capabilities.
package embedding

import (
	"context"
)

// Provider defines the interface for embedding providers.
//
// This interface is implemented by all embedding model providers
// and allows the application to generate embeddings for text.
//
// Example implementation:
//
//     type LocalProvider struct {
//         model  *LocalModel
//         dimension int
//     }
//
//     func (p *LocalProvider) Embed(ctx context.Context, texts []string) ([][]float32, error) {
//         // Generate embeddings using local model
//     }
//
//     func (p *LocalProvider) Dimension() int {
//         return p.dimension
//     }
type Provider interface {
	// Embed generates embeddings for the given texts.
	//
	// Parameters:
	// - ctx: Context for cancellation and timeout
	// - texts: Slice of texts to embed
	//
	// Returns:
	// - [][]float32: Slice of embeddings, one for each text
	// - error: Error if embedding generation fails
	Embed(ctx context.Context, texts []string) ([][]float32, error)
	
	// Dimension returns the dimension of the embeddings generated by this provider.
	//
	// Returns:
	// - int: Embedding dimension
	Dimension() int
}
